version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: elasticsearch
    ports:
    - "9200:9200"
    volumes:
    - ./elasticsearch-data:/usr/share/elasticsearch/data
    networks:
    - docker-network
    restart: always
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports:
    - "5601:5601"
    depends_on:
    - elasticsearch
    networks:
    - docker-network
    # volumes:
    #   - ./kibana/config/:/usr/share/kibana/config:ro    
    restart: always
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    container_name: logstash
    depends_on:
    - elasticsearch
    networks:
    - docker-network
    ports:
    - "9600:9600"
    - "5000:5000"
    - "5044:5044"
    - "8080:8080"
    volumes:
    - ./logstash/config:/usr/share/logstash/pipeline/
    - ./debug:/var/log/
    restart: always
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
  
networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: 